image: thecjw/docker-android-java8

before_script:
  - pwd

stages:
  - build

debug:
  stage: build
  except:
    - release
  script:
    - ls ./*/gradlew | xargs dirname | xargs -I % sh -c 'cd %;chmod +x gradlew;./gradlew assembleDebug;'

release:
  stage: build
  only:
    - release
  script:
    - ls ./*/gradlew | xargs dirname | xargs -I % sh -c 'cd %;chmod +x gradlew;./gradlew assembleDebug;'
