image: thecjw/docker-android-java8

before_script:
  - pwd

stages:
  - build

debug:
  stage: build
  except:
    - release
  script:
    - chmod +x ./build.sh
    - ./build.sh

release:
  stage: build
  only:
    - release
  script:
    - chmod +x ./build.sh
    - ./build.sh
