language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-24

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - cd $TRAVIS_BUILD_DIR/
    - ls $(pwd)/*/gradlew
    - chmod +x ./build.sh
    - ./build.sh
